version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    
  redis:
    image: redis:5
    restart: "on-failure"
    container_name: redis
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - 6379:6379
    volumes:
      - ../redisdb:/data

  celery: &celery
    restart: "always"
    build: .
    image: celery
    command: celery --app=blog.celery:app worker -B --loglevel=DEBUG
    depends_on:
      - redis
      - db

  web:
    build: .
    command: bash -c "./docker_entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data: