# Generated by Django 2.2 on 2022-07-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220724_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='amount_of_upvotes',
        ),
    ]
